package com.inso.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import com.inso.entity.Member;

public interface MemberDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Delete({
        "delete from member",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer memberId);

    
    
    @Delete({
    	"<script>",
	        "delete from member",
	        "where member_id in",
		        "<foreach collection='datas' item='id' open='(' separator=',' close=')'>",
		        "#{id}",
		        "</foreach>",
        "</script>"
    })
    int deleteByAll(@Param("datas")int[] datas);

    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Insert({
        "insert into member (member_id, member_garde, ",
        "member_lipin, member_lastTime)",
        "values (#{memberId,jdbcType=INTEGER}, #{memberGarde,jdbcType=INTEGER}, ",
        "#{memberLipin,jdbcType=VARCHAR}, #{memberLasttime,jdbcType=TIMESTAMP})"
    })
    int insert(Member record);

 

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Select({
        "select",
        "member_id, member_garde, member_lipin, member_lastTime",
        "from member",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_garde", property="memberGarde", jdbcType=JdbcType.INTEGER),
        @Result(column="member_lipin", property="memberLipin", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_lastTime", property="memberLasttime", jdbcType=JdbcType.TIMESTAMP)
    })
    Member selectByPrimaryKey(Integer memberId);

    
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Select({
        "select",
        "member_id, member_garde, member_lipin, member_lastTime",
        "from member",
    })
    @Results({
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_garde", property="memberGarde", jdbcType=JdbcType.INTEGER),
        @Result(column="member_lipin", property="memberLipin", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_lastTime", property="memberLasttime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Member> selectAllMember();
    
    
    /**
     * 模糊查询
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Select({
        "select",
        "member_id, member_garde, member_lipin, member_lastTime",
        "from member",
        "where member_garde = #{memberGarde,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_garde", property="memberGarde", jdbcType=JdbcType.INTEGER),
        @Result(column="member_lipin", property="memberLipin", jdbcType=JdbcType.VARCHAR),
        @Result(column="member_lastTime", property="memberLasttime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Member> selectBymemberGarde(int memberGarde);
  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Update({
        "update member",
        "set member_garde = #{memberGarde,jdbcType=INTEGER},",
          "member_lipin = #{memberLipin,jdbcType=VARCHAR},",
          "member_lastTime = #{memberLasttime,jdbcType=TIMESTAMP}",
        "where member_id = #{memberId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Member record);
}