package com.inso.entity;

import java.sql.Timestamp;

public class Refund {
 
    private Integer chargeId;
    private String solderName;
    private Timestamp chargeTime;
    private String chargeReason;
    private Integer chargeNumber;
    
    
    public Integer getChargeId() {
        return chargeId;
    }

    public void setChargeId(Integer chargeId) {
        this.chargeId = chargeId;
    }
    public String getSolderName() {
        return solderName;
    }

    public void setSolderName(String solderName) {
        this.solderName = solderName == null ? null : solderName.trim();
    }

    public Timestamp getChargeTime() {
        return chargeTime;
    }


    public void setChargeTime(Timestamp chargeTime) {
        this.chargeTime = chargeTime;
    }


    public String getChargeReason() {
        return chargeReason;
    }


    public void setChargeReason(String chargeReason) {
        this.chargeReason = chargeReason == null ? null : chargeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.charge_number
     *
     * @return the value of charge.charge_number
     *
     * @mbggenerated Tue Nov 13 15:59:38 CST 2018
     */
    public Integer getChargeNumber() {
        return chargeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.charge_number
     *
     * @param chargeNumber the value for charge.charge_number
     *
     * @mbggenerated Tue Nov 13 15:59:38 CST 2018
     */
    public void setChargeNumber(Integer chargeNumber) {
        this.chargeNumber = chargeNumber;
    }

	public Refund() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Refund(String solderName, Timestamp chargeTime, String chargeReason,
                  Integer chargeNumber) {
		super();
		this.solderName = solderName;
		this.chargeTime = chargeTime;
		this.chargeReason = chargeReason;
		this.chargeNumber = chargeNumber;
	}

	public Refund(Integer chargeId, String solderName, Timestamp chargeTime,
                  String chargeReason, Integer chargeNumber) {
		super();
		this.chargeId = chargeId;
		this.solderName = solderName;
		this.chargeTime = chargeTime;
		this.chargeReason = chargeReason;
		this.chargeNumber = chargeNumber;
	}
    
    
}